// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApXysExarJMuWjIayvaLf2JtC0x8s96OE',
    appId: '1:57139749950:web:6407f28c23972589435d6f',
    messagingSenderId: '57139749950',
    projectId: 'fb-auth-riverpod-2023',
    authDomain: 'fb-auth-riverpod-2023.firebaseapp.com',
    storageBucket: 'fb-auth-riverpod-2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2-rOP0CEzL_Z8aXPtQZrsv7lRSmoaCdA',
    appId: '1:57139749950:android:7fe602019619b49a435d6f',
    messagingSenderId: '57139749950',
    projectId: 'fb-auth-riverpod-2023',
    storageBucket: 'fb-auth-riverpod-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCwlZLUq-OIQW46tTrPZL9kfIwj1ok7Tg',
    appId: '1:57139749950:ios:353f5cfb9351f119435d6f',
    messagingSenderId: '57139749950',
    projectId: 'fb-auth-riverpod-2023',
    storageBucket: 'fb-auth-riverpod-2023.appspot.com',
    iosBundleId: 'com.example.fbAuthRiverpod',
  );
}
